### ISSUE TITLE
[Feature Request]

### ISSUE THREAD

**Issue by HBDrew** [AndreWohnsland/CocktailBerry#107]
**Is your feature request related to a problem? Please describe.**
Not a problem, just an improvement for cleaning. It would be awesome to have a relay to switch the pump directions for cleaning. This would allow for backing the liquid out of the lines both before and after cleaning. 

**Describe the solution you'd like**
An option to control a single relay to reverse all pumps for cleaning. 

**Alternative***
I have considered a separate physical switch to perform this and it may be the easiest solution, but certainly isn’t as fun! :-)

**Comment by AndreWohnsland** [comment]
Hey, this sounds for a good addition. 
To understand the technical needed details: the inversion/switching of the pump direction is just the activation of the Relais over an additional (let it call the inverter pin for now) for the duration of the inversion?

I can imagine one of two flows: 
1. before cleaning, the inverter relais could be activated, then the pumps would activate a short period, the inversion stops and the regular cleaning begins and after that the inversion once again activates and the remaining fluid is flown in the opposite direction again.
2. There is a separate option called inverse cleaning (or similar) the user can click instead of cleaning, this would work like the cleaning but activated the inverter Relais before and deactivates after the process.

Currently leaning towards option 2 since one may want to go a cleaning or inverse step multiple times if needed.

**Comment by HBDrew** [comment]
Yes, that’s how I envisioned it working. Just switches the the relays (it would technically require two relays, but still one channel)I like your idea on option 2, it gives more flexibility.Wiring would look something like this: AndrewOn Oct 15, 2023, at 12:22, Andre Wohnsland ***@***.***> wrote:﻿
Hey, this sounds for a good addition.
To understand the technical needed details: the inversion/switching of the pump direction is just the activation of the Relais over an additional (let it call the inverter pin for now) for the duration of the inversion?
I can imagine one of two flows:

before cleaning, the inverter relais could be activated, then the pumps would activate a short period, the inversion stops and the regular cleaning begins and after that the inversion once again activates and the remaining fluid is flown in the opposite direction again.
There is a separate option called inverse cleaning (or similar) the user can click instead of cleaning, this would work like the cleaning but activated the inverter Relais before and deactivates after the process.

Currently leaning towards option 2 since one may want to go a cleaning or inverse step multiple times if needed.

**Comment by AndreWohnsland** [comment]
Hey @HBDrew, do you have any setup / software with which you could test the feature?
The current implementation will ask before starting the cleaning (if reversion option is activated) if to revert the cleaning. If prompted with yes, the cleaning will start reverted, otherwise it will start normally. Users not having this option enabled will not be prompted with this question. This was done to not clutter the UI with multiple clean buttons. In theory and code perspective it does work, but I can't validate it against physical hardware, since I have no bidirectional pumps nor a two current way setup. Anyway, I will release this feature with the next update, but you can already test it now if you switch to the "dev" branch after pulling the latest git status with `git pull`, if you want to check it out.

**Comment by HBDrew** [comment]
Fantastic! I’m building my setup right now, but should be at a point where I can test it this weekend. I’ll get it breadboarded and give it a go and let you know how it works.Thanks! AndrewOn Oct 16, 2023, at 10:04, Andre Wohnsland ***@***.***> wrote:﻿
Hey @HBDrew, do you have any setup / software with which you could test the feature?
The current implementation will ask before starting the cleaning (if reversion option is activated) if to revert the cleaning. If prompted with yes, the cleaning will start reverted, otherwise it will start normally. Users not having this option enabled will not be prompted with this question. This was done to not clutter the UI with multiple clean buttons. In theory and code perspective it does work, but I can't validate it against physical hardware, since I have no bidirectional pumps nor a two current way setup. Anyway, I will release this feature with the next update, but you can already test it now if you switch to the "dev" branch after pulling the latest git status with git pull, if you want to check it out.

**Comment by AndreWohnsland** [comment]
Hey, @HBDrew, were you able you test it? I would close this issue, unless you have any issues with the current status, but then you can always reopen the issue as well.

**Comment by HBDrew** [comment]
Hey there.I was able to do a little testing and didn’t have any luck getting it to work. I may have been doing something wrong, but no matter what pin I select it doesn’t seem to work. The program doesn’t launch, I get an error about GPIO configuration, and I then have to go back into the config file and set inversion back to false. It could be that I missed something… AndrewOn Oct 23, 2023, at 02:19, Andre Wohnsland ***@***.***> wrote:﻿
Hey, @HBDrew, were you able you test it? I would close this issue, unless you have any issues with the current status, but then you can always reopen the issue as well.

**Comment by AndreWohnsland** [comment]
Can you send me the error (or a picture) and the config file with it? Did you set all config over the program (GUI) or did you temper in the config file? Doing over the GUI, usually you won't be able to enter bad values, when entering values via an editor in the config, I can only check them for reason at program start and they may be faulty.

**Comment by AndreWohnsland** [comment]
Well, I think I found the Issue. Please update with the terminal (git pull) to the latest (1.27.1) version. This should then work properly (hopefully). If it was the error, I was able to recreate on one of my hardwares.

**Comment by AndreWohnsland** [comment]
> Well, I think I found the Issue. Please update with the terminal (git pull) to the latest (1.27.1) version. This should then work properly (hopefully). If it was the error, I was able to recreate on one of my hardwares.

@HBDrew Can you give me feedback if this works, when you tested it? :)

**Comment by HBDrew** [comment]
Just tested it. Seems to work! At least it switches a relay connected to the GPIO pin. I have to wire up the pumps still, as my project is transitioning from prototype to full version. Looks good! I would consider it closed.I’ll send pics of my completed project once it’s fully up and running.  AndrewOn Oct 23, 2023, at 10:18, Andre Wohnsland ***@***.***> wrote:﻿

Well, I think I found the Issue. Please update with the terminal (git pull) to the latest (1.27.1) version. This should then work properly (hopefully). If it was the error, I was able to recreate on one of my hardwares.

@HBDrew Can you give me feedback if this works, when you tested it? :)
