### ISSUE TITLE
More Pumps and volume of the tubes

### ISSUE THREAD

**Issue by MarcTheKi** [AndreWohnsland/CocktailBerry#13]
Hi Andre , 

very nice project!
but I have a few questions?
Is it possible to add more than ten pumps? 
And maybe it is a good feature that you can add the number of ml the pump should try to deliver on pump up? (Tube capacity)

Regards Marco

**Comment by AndreWohnsland** [comment]
Hey Marco,

In theory, you could add quite a lot more pumps than ten. But there are some limiting factors:
- **Display Size**: Most limiting currently is the display size of the QT app on the small screen, displaying more than 10 is near impossible, but with some bigger screen, you can overcome this issue
- **Controllable GPIO number of the RPi**: If you would use all, you could theoretically get up to 26 Controlling Pins
- **Controlling the relay**:  Usually you can use up to an 8-channel relay with one 5V control current from the Pi. The RPi has 2x5V outputs, so realistically speaking, up to 16 pumps can be controlled this way. Maybe there are other ways, but I have not tested controlling more relays than this.

So to answer the first question regarding the pump count, with the right set up (either one 16-channel relay or 2x8-channel relays) up to **16 pumps** could work this way, currently the most limiting factor being the GUI limiting the count to 10.  Increasing this number requires some changes in the code base and GUI, I rate this a low to medium work amount. Your screen should probably have a minimum pixel height of 800 pixels to properly display all 16 slots, since Qt is messy sometimes.

Out of my experience, the tube capacity only matters when you run the machine for the first time, or replace an empty bottle. Due to the tubes being quite thin, the fluid stays within the tube after the pump prepared the first cocktail. Usually, the volume within the tubes is not that much (half a meter tube having ~25 ml volume, my machine probably having 10 ml capacity in the whole tube from a pump to the outlet), since the tubes / pumps are quite small. \
Therefore, in my opinion, there is no need to implement this feature, since the little benefit outweighs the medium to high work and refactoring to existing parts needed, which would have to be done to make this possible.

Feel free to follow up on my answer, if there are still some unclear parts.

Regards Andre
